language: node_js
node_js:
  - 13

services:
  - docker

before_script:
  - cd udagram-api-feed
  - npm run build
  - cd ../udagram-api-user
  - npm run build
  - cd ..

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-api-feed shehabnagy1998/udagram-api-feed:v1
  - docker tag udagram-api-user shehabnagy1998/udagram-api-user:v1
  - docker tag udagram-reverseproxy shehabnagy1998/udagram-reverseproxy:v1
  - docker tag udagram-frontend shehabnagy1998/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push shehabnagy1998/udagram-api-feed:v2
  - docker push shehabnagy1998/udagram-api-user:v2
  - docker push shehabnagy1998/udagram-reverseproxy:v2
  - docker push shehabnagy1998/udagram-frontend:v2
